### ISSUE TITLE
Can not select PHP version 8.X

### ISSUE THREAD

**Issue by paulkre** [aaPanel/aaPanel#117]
It is not possible to set the PHP version for a website to 8.0 or 8.1, because those options do not appear in the list. It seems to be working with all versions below 7.X.

**Comment by idflorin** [comment]
**I can**. aaPanel's Requirements: CentOS 7, Ubuntu20, Debian10,  to ensure that it is a clean operating system, there is no other environment with Apache/Nginx/php/MySQL installed (the existing environment can not be installed)

**Comment by paulkre** [comment]
Strange... I encountered the problem using [the official Docker image](https://hub.docker.com/r/aapanel/aapanel).

### Steps to reproduce:

1. Start container of `aapanel/aapanel:lamp`
2. Install PHP 8.1
3. Try to select it for new website

**Comment by paulkre** [comment]
Ok it actually works when you install it normally without Docker. So I am going to close this.
