### ISSUE TITLE
Please use the correct Ingress

### ISSUE THREAD

**Issue by 828767** [aaPanel/aaPanel#132]
`Please use the correct Ingress`

login issues happened after update to 6.8.26, i had do these with `bt` command :

(1) Restart panel

(9) Clear panel cache

(10) Clear login limit

(11) Cancel entrance limit

(12) Cancel domain binding limit

(13) Cacel IP access limit

(14) View panel default info

(23) Turn off BasicAuth authentication      

(16) Repair panel (check for errors and update panel files to the latest version)

**Comment by cybersholt** [comment]
Had the same thing happen to me after updating last night.

**Comment by cdnf** [comment]
This should be a bug, the solution at this time is to actively add an entry restrictions:
```
echo "/xxx" > /www/server/panel/data/admin_path.pl
# /xxx 表示登录入口，按自己的喜好来
```

and then run `bt 1` to restart aapanel.

more: [服务器管理面板aaPanel使用中的一些问题汇总](https://sobaigu.com/Ingress-verification-failed-by-aapanel.html)
