### ISSUE TITLE
High Default Load on AAPanel Monitor - 96%

### ISSUE THREAD

**Issue by zeeshanhaider6236dev** [aaPanel/aaPanel#196]
Hello AAPanel,

I’m concerned about the default load shown as 96% on my AAPanel monitor. As you can see in the attached screenshot, my average load is typically between 2-4% on a 64-core dedicated bare-metal server. However, today the server has choked several times due to this high default load displayed by AAPanel. Is this a default setting in your panel? If so, why does it keep loading at such a high percentage? Please advise.

Thank you.
![image](https://github.com/user-attachments/assets/be7ac98d-c98c-455e-8f57-0ea2e3d7b25e)

**Comment by aaPanel** [comment]
eh... It's likely not a aapanel internal process, if you still this problem, please visit the aapanel forum: [https://www.aapanel.com/forum](url)
to get any helps.
