### ISSUE TITLE
Please Help What to do ?

### ISSUE THREAD

**Issue by subhampro** [aaPanel/aaPanel#25]
Site error: the ionCube PHP Loader needs to be installed. This is a widely used PHP extension for running ionCube protected PHP code, website security and malware blocking. Please visit get-loader.ioncube.com for install assistance.

**Comment by zeroinf** [comment]
http://prntscr.com/rwbsmy
aaPanel 6.6.3  ,just check

**Comment by aaPanel** [comment]
> Site error: the ionCube PHP Loader needs to be installed. This is a widely used PHP extension for running ionCube protected PHP code, website security and malware blocking. Please visit get-loader.ioncube.com for install assistance.


Problem solving methods and help, please go to the forum for help, thank you
