### ISSUE TITLE
Installing aapanel on digitalocean droplets

### ISSUE THREAD

**Issue by KhairulAzmi21** [aaPanel/aaPanel#47]
Hi all, 

I have one questions is there anyone have tried installing aapanel on droplet DO ? do you have any issue .
I am planning to install but when I try to install it says web service is already install .

Therefore I discontinue installation process.

**Comment by idflorin** [comment]
You need a clean droplet. Be aware digitalocean blocks port 25.

**Comment by KhairulAzmi21** [comment]
Thanks
