### ISSUE TITLE
URL rewrite enabled

### ISSUE THREAD

**Issue by SniffRx** [aaPanel/aaPanel#50]
How do I enable rewrite in nginx ?
This dosn't work
![image](https://user-images.githubusercontent.com/37187657/106322323-be227100-6286-11eb-8198-b53f9242ac23.png)

**Comment by idflorin** [comment]
Like this
https://doc.aapanel.com/web/#/3?page_id=135

**Comment by SniffRx** [comment]
I try, but don't work
https://azuriom.com/en/docs/installation

**Comment by idflorin** [comment]
Do you have a public directory?
From this, I see that https://azuriom.com/en/docs was created with the PHP framework Laravel 8.
and from this
https://www.digitalocean.com/community/tutorials/how-to-deploy-a-laravel-application-with-nginx-on-ubuntu-16-04
I see Laravel using a /var/www/html/quickstart/public
I think you need to setup a running web directory first
https://prnt.sc/xu1vo1
and second a rewrite rule
`    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }`
