### ISSUE TITLE
change the host on which aaPanel runs

### ISSUE THREAD

**Issue by mzfr** [aaPanel/aaPanel#68]
Hey,

I am trying to run aaPanel internally i.e on `127.0.0.1` so only I can access it within my server and no one from outside can see it. 

I tried to change the [`HOST` in `runserver.py`](https://github.com/aaPanel/aaPanel/blob/master/runserver.py#L15) but that didn't work.

I also tried to change the `LOCAL_IP` in the `/etc/init.d/bt` file but that didn't work either.

Can you please tell me how can I start this with `127.0.0.1` as the host

Thanks

**Comment by c-ridgway** [comment]
The firewall should block external connections, not local.
