### ISSUE TITLE
Application submissions? 

### ISSUE THREAD

**Issue by rodber** [aaPanel/aaPanel#75]
I noticed that this supports applications as "one-click" stuff but I was unable to find any documentation or how-to for submitting my application to your listings.

I make [Chevereto](https://chevereto.com) and I would like to contribute the code needed for making this happen. Please let me know the procedure for doing that if this is an option.

Sorry if this is not the place to ask for.

**Comment by Liang2580** [comment]
For the one click code warehouse, this function can only be launched in September

**Comment by rodber** [comment]
Bueno gracias.
